### ISSUE TITLE
BUG: Remap partition number from destination cluster to source cluster when booting up to reset offset

### ISSUE THREAD

**Issue by joeirimpan** [zerodha/kaf-relay#16]
https://github.com/zerodha/kaf-relay/blob/main/producer.go#L48
^ We allow mapping from partition X from source to partition Y to destination. We should remap this when we are pulling destination offsets for resetting consumer offsets.

**Comment by kalbhor** [comment]
Explored trying to fix this with the existing configuration. Since we're only mapping consumer topic to producer partition, we can't figure what partition to pick when reverse mapping from destination partition. I have opened #17 which requires specifying src -> dest partition in the config
